### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by harunthuo** [webelightdev/laravel-slider#2]
Hi guys

set up the package but noticed the view files are not being published? 

also there is no admin component based on this error:

**`View [admin.components.page] not found`**

**Comment by jayeshanandani** [comment]
Hi @harunthuo ,

Thanks for trying out the plugin. This is still in development and has not been updated lately. I will mention the same in README.

**Comment by harunthuo** [comment]
ok. thanks for getting back

**Comment by RayhanYulanda** [comment]
Is there any update? @harunthuo
